name: Webpage Healthcheck
on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'Target URL to validate (leave empty to use default from script)'
        required: false
        type: string
  # schedule:
  #   # Run every 6 hours
  #   - cron: '0 */6 * * *'

jobs:
  healthcheck:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    
    - name: Run Webpage Healthcheck
      working-directory: ./healthcheck
      env:
        TARGET_URL: ${{ inputs.target_url }}
      run: node validate-webpage.js
